music/config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'services#stats', as: 'stats'
  get '/new', to: 'services#new', as: 'new_service'
  post '/new', to: 'services#create'
  get '/songs', to: 'services#songs', as: 'songs'
  get '/services', to: 'services#services', as: 'services'
end

music/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music/app/models/book.rb
class Book < ApplicationRecord
  include ActiveModel::Serializers::JSON
  has_many :songs, -> { order(:number) }
end

music/app/models/congregation.rb
class Congregation < ApplicationRecord
  include ActiveModel::Serializers::JSON
  has_many :services
end

music/app/models/service.rb
class Service < ApplicationRecord
  include ActiveModel::Serializers::JSON
  belongs_to :congregation, optional: true
  has_many :service_songs, -> { order(:position) }
  has_many :songs, through: :service_songs

  def self.from_email(date, body, congregation)
    service = self.find_or_create_by!(date: date, congregation: congregation)
    re = /(tis|at\w\w?) (\d+) (.*)$/i
    nb_re = /NB (.*)$/i
    song_count = 1
    service.service_songs.destroy_all
    body.each_line do |line|
      if m = re.match(line)
        book = Book.find_by!(acronym: m[1].upcase)
        song = Song.find_or_create_by!(book: book, number: m[2]) do |s|
          s.title = m[3].strip
        end
        ServiceSong.create!(song: song, service: service, position: song_count)
        song_count += 1
      elsif m = nb_re.match(line)
        song = Song.find_or_create_by!(title: m[1].strip)
        ServiceSong.create!(song: song, service: service, position: song_count)
        song_count += 1
      end
    end
    return service
  end
end

music/app/models/service_song.rb
class ServiceSong < ApplicationRecord
  belongs_to :song
  belongs_to :service
end

music/app/models/song.rb
class Song < ApplicationRecord
  include ActiveModel::Serializers::JSON
  belongs_to :book, optional: true
  has_many :service_songs
  has_many :services, through: :service_songs
end

music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

music/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def new
    @congregations = Congregation.all
    if params[:last]
      @last = Service.find_by(date: Date.parse(params[:last]))
      @resource = OpenStruct.new(date: @last.date + 7, body: "", congregation_id: @last.congregation_id)
    else
      @resource = OpenStruct.new(date: Date.today.beginning_of_week(:sunday), body: "")
    end
  end

  def create
    @resource = OpenStruct.new(date: Date.parse(params[:resource][:date]), body: params[:resource][:body],
                               congregation_id: params[:resource][:congregation_id])
    begin
      congregation = Congregation.find_by(id: params[:resource][:congregation_id])
      s = Service.from_email(params[:resource][:date], params[:resource][:body],
                             congregation)
    rescue Exception => e
      flash[:alert] = e.to_s
      render :new
      return
    end
    redirect_to new_service_path(last: s.date, congregation_id: params[:resource][:congregation_id])
  end

  def songs
    @cutoff = params[:cutoff].to_f
    @books = Book.includes(songs: :services).all
    @other_songs = Song.where(book: nil).order(:title).includes(:services)
  end

  def services
    @services = Service.includes(songs: :book).order(:date)
  end

  def stats
  end
end

music/app/helpers/application_helper.rb
module ApplicationHelper
end

music/app/helpers/service_helper.rb
module ServiceHelper
  def percent(numerator, denominator)
    sprintf('%.0f%%', numerator / denominator.to_f * 100)
  end

  def count_and_percent(numerator, denominator)
    "#{numerator} (#{percent(numerator, denominator)})"
  end
end

music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="alert"><%= flash[:alert] %></p>
    <p id="notice"><%= flash[:notice] %></p>
    <%= yield %>
  </body>
</html>

music/app/views/services/_nav.html.haml
%ul.links
  - if !current_page?(stats_path)
    %li= link_to('stats', stats_path)
  - else
    %li stats
  - if !current_page?(services_path)
    %li= link_to('services', services_path)
  - else
    %li services
  - if !current_page?(songs_path)
    %li= link_to('songs', songs_path)
  - else
    %li songs
  - if !current_page?(new_service_path)
    %li= link_to('new service', new_service_path)
  - else
    %li new service

music/app/views/services/new.html.haml
= render 'nav'

%h1 Music
- if @last
  %h2 Service created for #{@last.date} with songs
  %ol
    - @last.songs.order('service_songs.position').each do |song|
      - if song.book
        %li #{song.book.acronym} #{song.number} #{song.title}
      - else
        %li #{song.title}

%h2 Enter next service
= form_for :resource, url: new_service_path do |f|
  %p= f.label :congregation_id, 'Congregation'
  %p= f.collection_select :congregation_id, @congregations, :id, :name, :include_blank => true
  %p= f.label :date, 'Service date'
  %p= f.date_field :date
  %p= f.label :body, 'Song list'
  %p= f.text_area :body, size: '60x8'
  %p= f.submit

music/app/views/services/services.html.haml
= render 'nav'

%h1 Services

%p Total services: #{@services.length}
%p First service: #{@services.first.date.to_formatted_s(:long)}
%p Last service: #{@services.last.date.to_formatted_s(:long)}

- @services.each do |service|
  %h2 #{service.date}
  %ol
    - service.songs.each do |song|
      - if song.book
        %li #{song.book.acronym} #{song.number} #{song.title}
      - else
        %li #{song.title}

music/app/views/services/songs.html.haml
= render 'nav'

%h1 Songs
- @books.each do |book|
  %h2 #{book.title}
  %table
    %thead
      %tr
        %th Num
        %th Title
        %th Frequency
    %tbody
      - book.songs.each do |song|
        -if song.services.length >= @cutoff
          %tr
            %td #{song.number}
            %td #{song.title}
            %td #{song.services.length}

%h2 Other
%table
  %thead
    %tr
      %th Title
      %th Frequency
  %tbody
    - @other_songs.each do |song|
      - if song.services.length >= @cutoff
        %tr
          %td #{song.title}
          %td #{song.services.length}

music/app/views/services/stats.html.haml
= render "nav"

%h1 Stats

%p
  - if Service.count > 0
    Out of #{Service.count} services,
    starting on #{Service.order(:date).first.date.to_formatted_s(:long)}
    and ending on #{Service.order(:date).last.date.to_formatted_s(:long)},
    there were #{Song.count} different songs.
  - else
    No services yet!

%p Songs per book
%ul
  - Song.group(:book).order('count_all DESC').count.each do |book, count|
    - if book
      %li #{book.title}: #{count}
    - else
      %li Other: #{count}

%p Most frequently sung songs
- song_counts = ServiceSong.group(:song).order('count_all DESC').count
- min_songs = [song_counts.length, 10].min
- to_count = song_counts.values[min_songs - 1]
%ul
  - song_counts.each do |song, count|
    - break if count < to_count
    %li #{song.book&.acronym} #{song.number} #{song.title}: #{count}

%p Proportion of songs sung a particular number of times
- counts = song_counts.values.each_with_object(Hash.new(0)) do |count, hash|
  - hash[count] += 1
- total_songs = counts.values.sum
%ul
  %li Songs sung once: #{count_and_percent(counts[1], total_songs)}
  %li Songs sung twice: #{count_and_percent(counts[2], total_songs)}
  %li Songs sung three times: #{count_and_percent(counts[3], total_songs)}
  %li Songs sung four or more times: #{count_and_percent(counts.select{|k| k>=4}.values.sum, total_songs)}